# Codecov Configuration for Verity Systems
# Coverage reporting for AI Fact-Checking Platform
# GitHub Education: Free for open source projects

codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "50...100"
  
  status:
    project:
      default:
        # Target 70% coverage for the whole project
        target: 70%
        threshold: 2%
        # Only fail if coverage drops
        if_ci_failed: error
    
    patch:
      default:
        # New code should have 80% coverage
        target: 80%
        threshold: 5%
        # Don't require coverage on patches if CI fails
        if_ci_failed: success

# Ignore certain files/folders
ignore:
  - "python-tools/test_*.py"
  - "python-tools/__pycache__/**"
  - "**/migrations/**"
  - "**/*.html"
  - "**/*.css"
  - "**/*.js"

# Flags for different test types
flags:
  unittests:
    paths:
      - python-tools/
    carryforward: true
    after_n_builds: 1

  integration:
    paths:
      - python-tools/
    carryforward: true

# Comment configuration
comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: yes
  require_base: yes
  require_head: yes
  # Only post comment if coverage changes
  after_n_builds: 1

# Parsers
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

# GitHub-specific settings
github_checks:
  annotations: true
